// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avn/connect/v1/country.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avn.Connect.V1 {

  /// <summary>Holder for reflection information generated from avn/connect/v1/country.proto</summary>
  public static partial class CountryReflection {

    #region Descriptor
    /// <summary>File descriptor for avn/connect/v1/country.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CountryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxhdm4vY29ubmVjdC92MS9jb3VudHJ5LnByb3RvEg5hdm4uY29ubmVjdC52",
            "MSK6AQoHQ291bnRyeRISCgpjb3VudHJ5X2lkGAEgASgJEgwKBG5hbWUYAyAB",
            "KAkSFAoMbmFtZV9lbmdsaXNoGAQgASgJEhsKE2RlZmF1bHRfbGFuZ3VhZ2Vf",
            "aWQYBSABKAkSGQoRZGVmYXVsdF9sb2NhbGVfaWQYBiABKAkSHwoXZGVmYXVs",
            "dF9vcmdhbml6YXRpb25faWQYByABKAUSEwoGdGFnX2lkGAggASgFSACIAQFC",
            "CQoHX3RhZ19pZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.Country), global::Avn.Connect.V1.Country.Parser, new[]{ "CountryId", "Name", "NameEnglish", "DefaultLanguageId", "DefaultLocaleId", "DefaultOrganizationId", "TagId" }, new[]{ "TagId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Country : pb::IMessage<Country>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Country> _parser = new pb::MessageParser<Country>(() => new Country());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Country> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.CountryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Country() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Country(Country other) : this() {
      _hasBits0 = other._hasBits0;
      countryId_ = other.countryId_;
      name_ = other.name_;
      nameEnglish_ = other.nameEnglish_;
      defaultLanguageId_ = other.defaultLanguageId_;
      defaultLocaleId_ = other.defaultLocaleId_;
      defaultOrganizationId_ = other.defaultOrganizationId_;
      tagId_ = other.tagId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Country Clone() {
      return new Country(this);
    }

    /// <summary>Field number for the "country_id" field.</summary>
    public const int CountryIdFieldNumber = 1;
    private string countryId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountryId {
      get { return countryId_; }
      set {
        countryId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name_english" field.</summary>
    public const int NameEnglishFieldNumber = 4;
    private string nameEnglish_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NameEnglish {
      get { return nameEnglish_; }
      set {
        nameEnglish_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "default_language_id" field.</summary>
    public const int DefaultLanguageIdFieldNumber = 5;
    private string defaultLanguageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefaultLanguageId {
      get { return defaultLanguageId_; }
      set {
        defaultLanguageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "default_locale_id" field.</summary>
    public const int DefaultLocaleIdFieldNumber = 6;
    private string defaultLocaleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefaultLocaleId {
      get { return defaultLocaleId_; }
      set {
        defaultLocaleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "default_organization_id" field.</summary>
    public const int DefaultOrganizationIdFieldNumber = 7;
    private int defaultOrganizationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DefaultOrganizationId {
      get { return defaultOrganizationId_; }
      set {
        defaultOrganizationId_ = value;
      }
    }

    /// <summary>Field number for the "tag_id" field.</summary>
    public const int TagIdFieldNumber = 8;
    private readonly static int TagIdDefaultValue = 0;

    private int tagId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TagId {
      get { if ((_hasBits0 & 1) != 0) { return tagId_; } else { return TagIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        tagId_ = value;
      }
    }
    /// <summary>Gets whether the "tag_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTagId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "tag_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTagId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Country);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Country other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CountryId != other.CountryId) return false;
      if (Name != other.Name) return false;
      if (NameEnglish != other.NameEnglish) return false;
      if (DefaultLanguageId != other.DefaultLanguageId) return false;
      if (DefaultLocaleId != other.DefaultLocaleId) return false;
      if (DefaultOrganizationId != other.DefaultOrganizationId) return false;
      if (TagId != other.TagId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CountryId.Length != 0) hash ^= CountryId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (NameEnglish.Length != 0) hash ^= NameEnglish.GetHashCode();
      if (DefaultLanguageId.Length != 0) hash ^= DefaultLanguageId.GetHashCode();
      if (DefaultLocaleId.Length != 0) hash ^= DefaultLocaleId.GetHashCode();
      if (DefaultOrganizationId != 0) hash ^= DefaultOrganizationId.GetHashCode();
      if (HasTagId) hash ^= TagId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CountryId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountryId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameEnglish.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameEnglish);
      }
      if (DefaultLanguageId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DefaultLanguageId);
      }
      if (DefaultLocaleId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DefaultLocaleId);
      }
      if (DefaultOrganizationId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(DefaultOrganizationId);
      }
      if (HasTagId) {
        output.WriteRawTag(64);
        output.WriteInt32(TagId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CountryId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountryId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameEnglish.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameEnglish);
      }
      if (DefaultLanguageId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DefaultLanguageId);
      }
      if (DefaultLocaleId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DefaultLocaleId);
      }
      if (DefaultOrganizationId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(DefaultOrganizationId);
      }
      if (HasTagId) {
        output.WriteRawTag(64);
        output.WriteInt32(TagId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CountryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountryId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (NameEnglish.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameEnglish);
      }
      if (DefaultLanguageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefaultLanguageId);
      }
      if (DefaultLocaleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefaultLocaleId);
      }
      if (DefaultOrganizationId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefaultOrganizationId);
      }
      if (HasTagId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TagId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Country other) {
      if (other == null) {
        return;
      }
      if (other.CountryId.Length != 0) {
        CountryId = other.CountryId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.NameEnglish.Length != 0) {
        NameEnglish = other.NameEnglish;
      }
      if (other.DefaultLanguageId.Length != 0) {
        DefaultLanguageId = other.DefaultLanguageId;
      }
      if (other.DefaultLocaleId.Length != 0) {
        DefaultLocaleId = other.DefaultLocaleId;
      }
      if (other.DefaultOrganizationId != 0) {
        DefaultOrganizationId = other.DefaultOrganizationId;
      }
      if (other.HasTagId) {
        TagId = other.TagId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CountryId = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameEnglish = input.ReadString();
            break;
          }
          case 42: {
            DefaultLanguageId = input.ReadString();
            break;
          }
          case 50: {
            DefaultLocaleId = input.ReadString();
            break;
          }
          case 56: {
            DefaultOrganizationId = input.ReadInt32();
            break;
          }
          case 64: {
            TagId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CountryId = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameEnglish = input.ReadString();
            break;
          }
          case 42: {
            DefaultLanguageId = input.ReadString();
            break;
          }
          case 50: {
            DefaultLocaleId = input.ReadString();
            break;
          }
          case 56: {
            DefaultOrganizationId = input.ReadInt32();
            break;
          }
          case 64: {
            TagId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
