// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avn/connect/v1/authorization.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avn.Connect.V1 {

  /// <summary>Holder for reflection information generated from avn/connect/v1/authorization.proto</summary>
  public static partial class AuthorizationReflection {

    #region Descriptor
    /// <summary>File descriptor for avn/connect/v1/authorization.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthorizationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJhdm4vY29ubmVjdC92MS9hdXRob3JpemF0aW9uLnByb3RvEg5hdm4uY29u",
            "bmVjdC52MRogYXZuL2Nvbm5lY3QvdjEvY3JlZGVudGlhbHMucHJvdG8ilwMK",
            "DUF1dGhvcml6YXRpb24SFQoIdXNlcl9qd3QYASABKAlIAIgBARIZCgxkaW1l",
            "bnNpb25faWQYAiABKAlIAYgBARJKChZjb25uZWN0aW9uX2NyZWRlbnRpYWxz",
            "GAMgASgLMiUuYXZuLmNvbm5lY3QudjEuQ29ubmVjdGlvbkNyZWRlbnRpYWxz",
            "SAKIAQESGQoMdXNlcl9hcGlfa2V5GAQgASgJSAOIAQESFwoKZGV2aWNlX2p3",
            "dBgFIAEoCUgEiAEBEhQKB3Bhc3NfaWQYBiABKAlIBYgBARJCChJjbGllbnRf",
            "Y3JlZGVudGlhbHMYByABKAsyIS5hdm4uY29ubmVjdC52MS5DbGllbnRDcmVk",
            "ZW50aWFsc0gGiAEBQgsKCV91c2VyX2p3dEIPCg1fZGltZW5zaW9uX2lkQhkK",
            "F19jb25uZWN0aW9uX2NyZWRlbnRpYWxzQg8KDV91c2VyX2FwaV9rZXlCDQoL",
            "X2RldmljZV9qd3RCCgoIX3Bhc3NfaWRCFQoTX2NsaWVudF9jcmVkZW50aWFs",
            "cyI+Cg9BdXRoT25seVJlcXVlc3QSKwoEYXV0aBgBIAEoCzIdLmF2bi5jb25u",
            "ZWN0LnYxLkF1dGhvcml6YXRpb24q+AEKEElkZW50aXR5UHJvdmlkZXISIQod",
            "SURFTlRJVFlfUFJPVklERVJfVU5TUEVDSUZJRUQQABIfChtJREVOVElUWV9Q",
            "Uk9WSURFUl9BTk9OWU1PVVMQARIiCh5JREVOVElUWV9QUk9WSURFUl9DTEFT",
            "U0NPTk5FQ1QQAhIcChhJREVOVElUWV9QUk9WSURFUl9HT09HTEUQAxIfChtJ",
            "REVOVElUWV9QUk9WSURFUl9NSUNST1NPRlQQBBIcChhJREVOVElUWV9QUk9W",
            "SURFUl9DTEVWRVIQBRIfChtJREVOVElUWV9QUk9WSURFUl9DTEFTU0xJTksQ",
            "BmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avn.Connect.V1.CredentialsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Avn.Connect.V1.IdentityProvider), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.Authorization), global::Avn.Connect.V1.Authorization.Parser, new[]{ "UserJwt", "DimensionId", "ConnectionCredentials", "UserApiKey", "DeviceJwt", "PassId", "ClientCredentials" }, new[]{ "UserJwt", "DimensionId", "ConnectionCredentials", "UserApiKey", "DeviceJwt", "PassId", "ClientCredentials" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.AuthOnlyRequest), global::Avn.Connect.V1.AuthOnlyRequest.Parser, new[]{ "Auth" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum IdentityProvider {
    [pbr::OriginalName("IDENTITY_PROVIDER_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("IDENTITY_PROVIDER_ANONYMOUS")] Anonymous = 1,
    [pbr::OriginalName("IDENTITY_PROVIDER_CLASSCONNECT")] Classconnect = 2,
    [pbr::OriginalName("IDENTITY_PROVIDER_GOOGLE")] Google = 3,
    [pbr::OriginalName("IDENTITY_PROVIDER_MICROSOFT")] Microsoft = 4,
    [pbr::OriginalName("IDENTITY_PROVIDER_CLEVER")] Clever = 5,
    [pbr::OriginalName("IDENTITY_PROVIDER_CLASSLINK")] Classlink = 6,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Authorization to content and services from one or more sources
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Authorization : pb::IMessage<Authorization>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Authorization> _parser = new pb::MessageParser<Authorization>(() => new Authorization());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Authorization> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.AuthorizationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Authorization() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Authorization(Authorization other) : this() {
      userJwt_ = other.userJwt_;
      dimensionId_ = other.dimensionId_;
      connectionCredentials_ = other.connectionCredentials_ != null ? other.connectionCredentials_.Clone() : null;
      userApiKey_ = other.userApiKey_;
      deviceJwt_ = other.deviceJwt_;
      passId_ = other.passId_;
      clientCredentials_ = other.clientCredentials_ != null ? other.clientCredentials_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Authorization Clone() {
      return new Authorization(this);
    }

    /// <summary>Field number for the "user_jwt" field.</summary>
    public const int UserJwtFieldNumber = 1;
    private readonly static string UserJwtDefaultValue = "";

    private string userJwt_;
    /// <summary>
    /// The OpenID JWT of the authenticated user
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserJwt {
      get { return userJwt_ ?? UserJwtDefaultValue; }
      set {
        userJwt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "user_jwt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUserJwt {
      get { return userJwt_ != null; }
    }
    /// <summary>Clears the value of the "user_jwt" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUserJwt() {
      userJwt_ = null;
    }

    /// <summary>Field number for the "dimension_id" field.</summary>
    public const int DimensionIdFieldNumber = 2;
    private readonly static string DimensionIdDefaultValue = "";

    private string dimensionId_;
    /// <summary>
    /// Dimensions have intrinsic authorization parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DimensionId {
      get { return dimensionId_ ?? DimensionIdDefaultValue; }
      set {
        dimensionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "dimension_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDimensionId {
      get { return dimensionId_ != null; }
    }
    /// <summary>Clears the value of the "dimension_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDimensionId() {
      dimensionId_ = null;
    }

    /// <summary>Field number for the "connection_credentials" field.</summary>
    public const int ConnectionCredentialsFieldNumber = 3;
    private global::Avn.Connect.V1.ConnectionCredentials connectionCredentials_;
    /// <summary>
    /// The dimension connection credentials
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.ConnectionCredentials ConnectionCredentials {
      get { return connectionCredentials_; }
      set {
        connectionCredentials_ = value;
      }
    }

    /// <summary>Field number for the "user_api_key" field.</summary>
    public const int UserApiKeyFieldNumber = 4;
    private readonly static string UserApiKeyDefaultValue = "";

    private string userApiKey_;
    /// <summary>
    /// API key used exlusively for CC1 legacy access
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserApiKey {
      get { return userApiKey_ ?? UserApiKeyDefaultValue; }
      set {
        userApiKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "user_api_key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUserApiKey {
      get { return userApiKey_ != null; }
    }
    /// <summary>Clears the value of the "user_api_key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUserApiKey() {
      userApiKey_ = null;
    }

    /// <summary>Field number for the "device_jwt" field.</summary>
    public const int DeviceJwtFieldNumber = 5;
    private readonly static string DeviceJwtDefaultValue = "";

    private string deviceJwt_;
    /// <summary>
    /// JWT for a device
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceJwt {
      get { return deviceJwt_ ?? DeviceJwtDefaultValue; }
      set {
        deviceJwt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "device_jwt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDeviceJwt {
      get { return deviceJwt_ != null; }
    }
    /// <summary>Clears the value of the "device_jwt" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDeviceJwt() {
      deviceJwt_ = null;
    }

    /// <summary>Field number for the "pass_id" field.</summary>
    public const int PassIdFieldNumber = 6;
    private readonly static string PassIdDefaultValue = "";

    private string passId_;
    /// <summary>
    /// Hall passes can grant content access
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PassId {
      get { return passId_ ?? PassIdDefaultValue; }
      set {
        passId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "pass_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPassId {
      get { return passId_ != null; }
    }
    /// <summary>Clears the value of the "pass_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPassId() {
      passId_ = null;
    }

    /// <summary>Field number for the "client_credentials" field.</summary>
    public const int ClientCredentialsFieldNumber = 7;
    private global::Avn.Connect.V1.ClientCredentials clientCredentials_;
    /// <summary>
    /// Simple client credentials
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.ClientCredentials ClientCredentials {
      get { return clientCredentials_; }
      set {
        clientCredentials_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Authorization);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Authorization other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserJwt != other.UserJwt) return false;
      if (DimensionId != other.DimensionId) return false;
      if (!object.Equals(ConnectionCredentials, other.ConnectionCredentials)) return false;
      if (UserApiKey != other.UserApiKey) return false;
      if (DeviceJwt != other.DeviceJwt) return false;
      if (PassId != other.PassId) return false;
      if (!object.Equals(ClientCredentials, other.ClientCredentials)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUserJwt) hash ^= UserJwt.GetHashCode();
      if (HasDimensionId) hash ^= DimensionId.GetHashCode();
      if (connectionCredentials_ != null) hash ^= ConnectionCredentials.GetHashCode();
      if (HasUserApiKey) hash ^= UserApiKey.GetHashCode();
      if (HasDeviceJwt) hash ^= DeviceJwt.GetHashCode();
      if (HasPassId) hash ^= PassId.GetHashCode();
      if (clientCredentials_ != null) hash ^= ClientCredentials.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUserJwt) {
        output.WriteRawTag(10);
        output.WriteString(UserJwt);
      }
      if (HasDimensionId) {
        output.WriteRawTag(18);
        output.WriteString(DimensionId);
      }
      if (connectionCredentials_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ConnectionCredentials);
      }
      if (HasUserApiKey) {
        output.WriteRawTag(34);
        output.WriteString(UserApiKey);
      }
      if (HasDeviceJwt) {
        output.WriteRawTag(42);
        output.WriteString(DeviceJwt);
      }
      if (HasPassId) {
        output.WriteRawTag(50);
        output.WriteString(PassId);
      }
      if (clientCredentials_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ClientCredentials);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUserJwt) {
        output.WriteRawTag(10);
        output.WriteString(UserJwt);
      }
      if (HasDimensionId) {
        output.WriteRawTag(18);
        output.WriteString(DimensionId);
      }
      if (connectionCredentials_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ConnectionCredentials);
      }
      if (HasUserApiKey) {
        output.WriteRawTag(34);
        output.WriteString(UserApiKey);
      }
      if (HasDeviceJwt) {
        output.WriteRawTag(42);
        output.WriteString(DeviceJwt);
      }
      if (HasPassId) {
        output.WriteRawTag(50);
        output.WriteString(PassId);
      }
      if (clientCredentials_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ClientCredentials);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUserJwt) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserJwt);
      }
      if (HasDimensionId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DimensionId);
      }
      if (connectionCredentials_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectionCredentials);
      }
      if (HasUserApiKey) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserApiKey);
      }
      if (HasDeviceJwt) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceJwt);
      }
      if (HasPassId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PassId);
      }
      if (clientCredentials_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientCredentials);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Authorization other) {
      if (other == null) {
        return;
      }
      if (other.HasUserJwt) {
        UserJwt = other.UserJwt;
      }
      if (other.HasDimensionId) {
        DimensionId = other.DimensionId;
      }
      if (other.connectionCredentials_ != null) {
        if (connectionCredentials_ == null) {
          ConnectionCredentials = new global::Avn.Connect.V1.ConnectionCredentials();
        }
        ConnectionCredentials.MergeFrom(other.ConnectionCredentials);
      }
      if (other.HasUserApiKey) {
        UserApiKey = other.UserApiKey;
      }
      if (other.HasDeviceJwt) {
        DeviceJwt = other.DeviceJwt;
      }
      if (other.HasPassId) {
        PassId = other.PassId;
      }
      if (other.clientCredentials_ != null) {
        if (clientCredentials_ == null) {
          ClientCredentials = new global::Avn.Connect.V1.ClientCredentials();
        }
        ClientCredentials.MergeFrom(other.ClientCredentials);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserJwt = input.ReadString();
            break;
          }
          case 18: {
            DimensionId = input.ReadString();
            break;
          }
          case 26: {
            if (connectionCredentials_ == null) {
              ConnectionCredentials = new global::Avn.Connect.V1.ConnectionCredentials();
            }
            input.ReadMessage(ConnectionCredentials);
            break;
          }
          case 34: {
            UserApiKey = input.ReadString();
            break;
          }
          case 42: {
            DeviceJwt = input.ReadString();
            break;
          }
          case 50: {
            PassId = input.ReadString();
            break;
          }
          case 58: {
            if (clientCredentials_ == null) {
              ClientCredentials = new global::Avn.Connect.V1.ClientCredentials();
            }
            input.ReadMessage(ClientCredentials);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserJwt = input.ReadString();
            break;
          }
          case 18: {
            DimensionId = input.ReadString();
            break;
          }
          case 26: {
            if (connectionCredentials_ == null) {
              ConnectionCredentials = new global::Avn.Connect.V1.ConnectionCredentials();
            }
            input.ReadMessage(ConnectionCredentials);
            break;
          }
          case 34: {
            UserApiKey = input.ReadString();
            break;
          }
          case 42: {
            DeviceJwt = input.ReadString();
            break;
          }
          case 50: {
            PassId = input.ReadString();
            break;
          }
          case 58: {
            if (clientCredentials_ == null) {
              ClientCredentials = new global::Avn.Connect.V1.ClientCredentials();
            }
            input.ReadMessage(ClientCredentials);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Utility message for services that only required authorization
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AuthOnlyRequest : pb::IMessage<AuthOnlyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthOnlyRequest> _parser = new pb::MessageParser<AuthOnlyRequest>(() => new AuthOnlyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthOnlyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.AuthorizationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthOnlyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthOnlyRequest(AuthOnlyRequest other) : this() {
      auth_ = other.auth_ != null ? other.auth_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthOnlyRequest Clone() {
      return new AuthOnlyRequest(this);
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 1;
    private global::Avn.Connect.V1.Authorization auth_;
    /// <summary>
    /// Authorization for the request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.Authorization Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthOnlyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthOnlyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Auth, other.Auth)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (auth_ != null) hash ^= Auth.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (auth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthOnlyRequest other) {
      if (other == null) {
        return;
      }
      if (other.auth_ != null) {
        if (auth_ == null) {
          Auth = new global::Avn.Connect.V1.Authorization();
        }
        Auth.MergeFrom(other.Auth);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (auth_ == null) {
              Auth = new global::Avn.Connect.V1.Authorization();
            }
            input.ReadMessage(Auth);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (auth_ == null) {
              Auth = new global::Avn.Connect.V1.Authorization();
            }
            input.ReadMessage(Auth);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
