// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avn/connect/v1/properties.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avn.Connect.V1 {

  /// <summary>Holder for reflection information generated from avn/connect/v1/properties.proto</summary>
  public static partial class PropertiesReflection {

    #region Descriptor
    /// <summary>File descriptor for avn/connect/v1/properties.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PropertiesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9hdm4vY29ubmVjdC92MS9wcm9wZXJ0aWVzLnByb3RvEg5hdm4uY29ubmVj",
            "dC52MRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxoiYXZuL2Nv",
            "bm5lY3QvdjEvYXV0aG9yaXphdGlvbi5wcm90bxohYXZuL2Nvbm5lY3QvdjEv",
            "dHJhbnNsYXRpb25zLnByb3RvGhphdm4vY29ubmVjdC92MS9tZWRpYS5wcm90",
            "byLfAQoaU2V0RW50aXR5UHJvcGVydGllc1JlcXVlc3QSKwoEYXV0aBgBIAEo",
            "CzIdLmF2bi5jb25uZWN0LnYxLkF1dGhvcml6YXRpb24SOwoRZW50aXR5X3By",
            "b3BlcnRpZXMYBCADKAsyIC5hdm4uY29ubmVjdC52MS5FbnRpdHlQcm9wZXJ0",
            "aWVzEhUKCWVudGl0eV9pZBgCIAEoBUICGAESQAoPcHJvcGVydHlfc3RhdGVz",
            "GAMgAygLMiMuYXZuLmNvbm5lY3QudjEuRW50aXR5UHJvcGVydHlTdGF0ZUIC",
            "GAEigAMKGkdldEVudGl0eVByb3BlcnRpZXNSZXF1ZXN0EisKBGF1dGgYASAB",
            "KAsyHS5hdm4uY29ubmVjdC52MS5BdXRob3JpemF0aW9uEhIKCmVudGl0eV9p",
            "ZHMYAiADKAUSMgoKcHJvcGVydGllcxgDIAMoDjIeLmF2bi5jb25uZWN0LnYx",
            "LkVudGl0eVByb3BlcnR5EjcKCXRyYW5zbGF0ZRgEIAEoCzIfLmF2bi5jb25u",
            "ZWN0LnYxLlRyYW5zbGF0aW9uU3BlY0gAiAEBEk8KC2ltYWdlX3NwZWNzGAUg",
            "AygLMjouYXZuLmNvbm5lY3QudjEuR2V0RW50aXR5UHJvcGVydGllc1JlcXVl",
            "c3QuSW1hZ2VTcGVjc0VudHJ5GlUKD0ltYWdlU3BlY3NFbnRyeRILCgNrZXkY",
            "ASABKAUSMQoFdmFsdWUYAiABKAsyIi5hdm4uY29ubmVjdC52MS5UcmFuc2Nv",
            "ZGVJbWFnZVNwZWM6AjgBQgwKCl90cmFuc2xhdGUiUAobR2V0RW50aXR5UHJv",
            "cGVydGllc1Jlc3BvbnNlEjEKB3Jlc3VsdHMYASADKAsyIC5hdm4uY29ubmVj",
            "dC52MS5FbnRpdHlQcm9wZXJ0aWVzImMKEEVudGl0eVByb3BlcnRpZXMSEQoJ",
            "ZW50aXR5X2lkGAEgASgFEjwKD3Byb3BlcnR5X3N0YXRlcxgCIAMoCzIjLmF2",
            "bi5jb25uZWN0LnYxLkVudGl0eVByb3BlcnR5U3RhdGUi+QEKE0VudGl0eVBy",
            "b3BlcnR5U3RhdGUSMAoIcHJvcGVydHkYAyABKA4yHi5hdm4uY29ubmVjdC52",
            "MS5FbnRpdHlQcm9wZXJ0eRIOCgRib29sGAQgASgISAASDwoFaW50MzIYBSAB",
            "KAVIABIPCgVpbnQ2NBgGIAEoA0gAEg8KBWZsb2F0GAcgASgCSAASEAoGZG91",
            "YmxlGAggASgBSAASEAoGc3RyaW5nGAkgASgJSAASDwoFYnl0ZXMYCiABKAxI",
            "ABIvCgl0aW1lc3RhbXAYCyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0",
            "YW1wSABCBwoFc3RhdGUqswsKDkVudGl0eVByb3BlcnR5Eh8KG0VOVElUWV9Q",
            "Uk9QRVJUWV9VTlNQRUNJRklFRBAAEhYKEkVOVElUWV9QUk9QRVJUWV9JRBAB",
            "EhgKFEVOVElUWV9QUk9QRVJUWV9OQU1FEAISHwobRU5USVRZX1BST1BFUlRZ",
            "X0RFU0NSSVBUSU9OEAMSGwoXRU5USVRZX1BST1BFUlRZX0NSRUFURUQQBBIb",
            "ChdFTlRJVFlfUFJPUEVSVFlfVVBEQVRFRBAFEhgKFEVOVElUWV9QUk9QRVJU",
            "WV9TSVpFEAYSIgoeRU5USVRZX1BST1BFUlRZX1BSSU9SSVRZX09SREVSEAcS",
            "HAoYRU5USVRZX1BST1BFUlRZX0lDT05fVVJMEAgSIAocRU5USVRZX1BST1BF",
            "UlRZX0lOU1RSVUNUSU9OUxAJEhsKF0VOVElUWV9QUk9QRVJUWV9DT05URVhU",
            "EAoSHAoYRU5USVRZX1BST1BFUlRZX0FTU0VUX0lEEAsSHwobRU5USVRZX1BS",
            "T1BFUlRZX0xBTkdVQUdFX0lEEAwSHQoZRU5USVRZX1BST1BFUlRZX1BVQkxJ",
            "U0hFRBANEh0KGUVOVElUWV9QUk9QRVJUWV9BVkFJTEFCTEUQDhIcChhFTlRJ",
            "VFlfUFJPUEVSVFlfRkVBVFVSRUQQDxIfChtFTlRJVFlfUFJPUEVSVFlfTUFD",
            "X0FERFJFU1MQEBIeChpFTlRJVFlfUFJPUEVSVFlfU1dfVkVSU0lPThAREhwK",
            "GEVOVElUWV9QUk9QRVJUWV9IT1NUTkFNRRASEhwKGEVOVElUWV9QUk9QRVJU",
            "WV9QTEFURk9STRATEhwKGEVOVElUWV9QUk9QRVJUWV9BUFBST1ZFRBAUEhwK",
            "GEVOVElUWV9QUk9QRVJUWV9GSUxFTkFNRRAVEh4KGkVOVElUWV9QUk9QRVJU",
            "WV9JVEVNX0NPVU5UEBYSHwobRU5USVRZX1BST1BFUlRZX1RSQUNLX0NPVU5U",
            "EBcSGAoURU5USVRZX1BST1BFUlRZX1RBR1MQGBIbChdFTlRJVFlfUFJPUEVS",
            "VFlfQUREUkVTUxAZEhgKFEVOVElUWV9QUk9QRVJUWV9DSVRZEBoSGQoVRU5U",
            "SVRZX1BST1BFUlRZX1NUQVRFEBsSHAoYRU5USVRZX1BST1BFUlRZX1BPU1RD",
            "T0RFEBwSGQoVRU5USVRZX1BST1BFUlRZX1BIT05FEB0SGQoVRU5USVRZX1BS",
            "T1BFUlRZX0VNQUlMEB4SHAoYRU5USVRZX1BST1BFUlRZX0tFWVdPUkRTEB8S",
            "GwoXRU5USVRZX1BST1BFUlRZX1NVTU1BUlkQIBIhCh1FTlRJVFlfUFJPUEVS",
            "VFlfQ09NQklORURfVEVYVBAhEhwKGEVOVElUWV9QUk9QRVJUWV9QSE9ORU1F",
            "UxAiEhwKGEVOVElUWV9QUk9QRVJUWV9QUklPUklUWRAjEh8KG0VOVElUWV9Q",
            "Uk9QRVJUWV9QUkVWSUVXX1VSTBAkEh0KGUVOVElUWV9QUk9QRVJUWV9QRVJN",
            "SVRURUQQJRIcChhFTlRJVFlfUFJPUEVSVFlfTElDRU5TRUQQJhIfChtFTlRJ",
            "VFlfUFJPUEVSVFlfRU5USVRZX1RZUEUQJxIjCh9FTlRJVFlfUFJPUEVSVFlf",
            "T1JHQU5JWkFUSU9OX0lEECgSHQoZRU5USVRZX1BST1BFUlRZX0RFVklDRV9J",
            "RBApEh8KG0VOVElUWV9QUk9QRVJUWV9XRUJTSVRFX1VSTBAqEiEKHUVOVElU",
            "WV9QUk9QRVJUWV9XQUxMUEFQRVJfVVJMECsSIwofRU5USVRZX1BST1BFUlRZ",
            "X1JFTEVBU0VfQ0hBTk5FTBAsEhwKGEVOVElUWV9QUk9QRVJUWV9GSVJNV0FS",
            "RRAtEh8KG0VOVElUWV9QUk9QRVJUWV9MQVNUX0FDQ0VTUxAuYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Avn.Connect.V1.AuthorizationReflection.Descriptor, global::Avn.Connect.V1.TranslationsReflection.Descriptor, global::Avn.Connect.V1.MediaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Avn.Connect.V1.EntityProperty), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.SetEntityPropertiesRequest), global::Avn.Connect.V1.SetEntityPropertiesRequest.Parser, new[]{ "Auth", "EntityProperties", "EntityId", "PropertyStates" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.GetEntityPropertiesRequest), global::Avn.Connect.V1.GetEntityPropertiesRequest.Parser, new[]{ "Auth", "EntityIds", "Properties", "Translate", "ImageSpecs" }, new[]{ "Translate" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.GetEntityPropertiesResponse), global::Avn.Connect.V1.GetEntityPropertiesResponse.Parser, new[]{ "Results" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.EntityProperties), global::Avn.Connect.V1.EntityProperties.Parser, new[]{ "EntityId", "PropertyStates" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.EntityPropertyState), global::Avn.Connect.V1.EntityPropertyState.Parser, new[]{ "Property", "Bool", "Int32", "Int64", "Float", "Double", "String", "Bytes", "Timestamp" }, new[]{ "State" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Entity properties. Not all properties are valid for all entity types.
  /// </summary>
  public enum EntityProperty {
    [pbr::OriginalName("ENTITY_PROPERTY_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Entity ID
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ID")] Id = 1,
    /// <summary>
    /// Entity name in plain text format
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_NAME")] Name = 2,
    /// <summary>
    /// Entity description stored in markdown format
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_DESCRIPTION")] Description = 3,
    /// <summary>
    /// Date entity was created
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_CREATED")] Created = 4,
    /// <summary>
    /// Date entity last updated
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_UPDATED")] Updated = 5,
    /// <summary>
    /// Entity size in bytes
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_SIZE")] Size = 6,
    /// <summary>
    /// Entity priority order (position within its parent; persisted as the sortorder column)
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PRIORITY_ORDER")] PriorityOrder = 7,
    /// <summary>
    /// Entity icon in PNG, JPEG, or SVG format
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ICON_URL")] IconUrl = 8,
    /// <summary>
    /// Entity instructions stored in markdown format
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_INSTRUCTIONS")] Instructions = 9,
    /// <summary>
    /// An indication of the origin of the entity
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_CONTEXT")] Context = 10,
    /// <summary>
    /// Entity asset ID
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ASSET_ID")] AssetId = 11,
    /// <summary>
    /// Content language
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_LANGUAGE_ID")] LanguageId = 12,
    /// <summary>
    /// Date entity was published
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PUBLISHED")] Published = 13,
    /// <summary>
    /// Is entity available, e.g. permitted or licensed?
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_AVAILABLE")] Available = 14,
    /// <summary>
    /// Date entity was featured
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_FEATURED")] Featured = 15,
    /// <summary>
    /// Entity MAC address
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_MAC_ADDRESS")] MacAddress = 16,
    /// <summary>
    /// Entity software version code
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_SW_VERSION")] SwVersion = 17,
    /// <summary>
    /// Entity hostname
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_HOSTNAME")] Hostname = 18,
    /// <summary>
    /// Entity platform
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PLATFORM")] Platform = 19,
    /// <summary>
    /// Date entity was approved
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_APPROVED")] Approved = 20,
    /// <summary>
    /// Entity filename
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_FILENAME")] Filename = 21,
    /// <summary>
    /// Entity child item cound
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ITEM_COUNT")] ItemCount = 22,
    /// <summary>
    /// Entity child track count
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_TRACK_COUNT")] TrackCount = 23,
    /// <summary>
    /// Entity tags
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_TAGS")] Tags = 24,
    /// <summary>
    /// Entity postal address
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ADDRESS")] Address = 25,
    /// <summary>
    /// Entity city
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_CITY")] City = 26,
    /// <summary>
    /// Entity state
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_STATE")] State = 27,
    /// <summary>
    /// Entity postal code
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_POSTCODE")] Postcode = 28,
    /// <summary>
    /// Entity phone number
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PHONE")] Phone = 29,
    /// <summary>
    /// Entity contact email
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_EMAIL")] Email = 30,
    /// <summary>
    /// Entity keywords
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_KEYWORDS")] Keywords = 31,
    /// <summary>
    /// Entity summary stored in markdown format
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_SUMMARY")] Summary = 32,
    /// <summary>
    /// Entity combined text
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_COMBINED_TEXT")] CombinedText = 33,
    /// <summary>
    /// Entity phonemes (IPA)
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PHONEMES")] Phonemes = 34,
    /// <summary>
    /// Entity priority
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PRIORITY")] Priority = 35,
    /// <summary>
    /// Entity preview URL
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PREVIEW_URL")] PreviewUrl = 36,
    /// <summary>
    /// Is entity permitted?
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_PERMITTED")] Permitted = 37,
    /// <summary>
    /// Is entity permitted?
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_LICENSED")] Licensed = 38,
    /// <summary>
    /// Entity type
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ENTITY_TYPE")] EntityType = 39,
    /// <summary>
    /// Owning organization ID for activities, categories, and profiles (0 means personally owned by the creator)
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_ORGANIZATION_ID")] OrganizationId = 40,
    /// <summary>
    /// Device ID
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_DEVICE_ID")] DeviceId = 41,
    /// <summary>
    /// Website URL for activities
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_WEBSITE_URL")] WebsiteUrl = 42,
    /// <summary>
    /// Wallpaper image for categories and profiles
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_WALLPAPER_URL")] WallpaperUrl = 43,
    /// <summary>
    /// Software release channel a device is tracking for updates. Carried as a string
    /// using the `ReleaseChannel` enum names (e.g. "PRODUCTION"); empty string means
    /// the device is not tracking any channel
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_RELEASE_CHANNEL")] ReleaseChannel = 44,
    /// <summary>
    /// Firmware build identifier reported by a device (raw build string)
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_FIRMWARE")] Firmware = 45,
    /// <summary>
    /// When a device last reported in (most recent check-in)
    /// </summary>
    [pbr::OriginalName("ENTITY_PROPERTY_LAST_ACCESS")] LastAccess = 46,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Generic message for entity property setting
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SetEntityPropertiesRequest : pb::IMessage<SetEntityPropertiesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetEntityPropertiesRequest> _parser = new pb::MessageParser<SetEntityPropertiesRequest>(() => new SetEntityPropertiesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SetEntityPropertiesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.PropertiesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetEntityPropertiesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetEntityPropertiesRequest(SetEntityPropertiesRequest other) : this() {
      auth_ = other.auth_ != null ? other.auth_.Clone() : null;
      entityProperties_ = other.entityProperties_.Clone();
      entityId_ = other.entityId_;
      propertyStates_ = other.propertyStates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetEntityPropertiesRequest Clone() {
      return new SetEntityPropertiesRequest(this);
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 1;
    private global::Avn.Connect.V1.Authorization auth_;
    /// <summary>
    /// Authorization for the request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.Authorization Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    /// <summary>Field number for the "entity_properties" field.</summary>
    public const int EntityPropertiesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.EntityProperties> _repeated_entityProperties_codec
        = pb::FieldCodec.ForMessage(34, global::Avn.Connect.V1.EntityProperties.Parser);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.EntityProperties> entityProperties_ = new pbc::RepeatedField<global::Avn.Connect.V1.EntityProperties>();
    /// <summary>
    /// Entity properties to update. A single request may modify at most 128 entities;
    /// larger requests are rejected. Batch bigger updates in groups of 128 or fewer.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.EntityProperties> EntityProperties {
      get { return entityProperties_; }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 2;
    private int entityId_;
    /// <summary>
    /// Entity to modify
    /// </summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "property_states" field.</summary>
    public const int PropertyStatesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.EntityPropertyState> _repeated_propertyStates_codec
        = pb::FieldCodec.ForMessage(26, global::Avn.Connect.V1.EntityPropertyState.Parser);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.EntityPropertyState> propertyStates_ = new pbc::RepeatedField<global::Avn.Connect.V1.EntityPropertyState>();
    /// <summary>
    /// Properties to modify
    /// </summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.EntityPropertyState> PropertyStates {
      get { return propertyStates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SetEntityPropertiesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SetEntityPropertiesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Auth, other.Auth)) return false;
      if(!entityProperties_.Equals(other.entityProperties_)) return false;
      if (EntityId != other.EntityId) return false;
      if(!propertyStates_.Equals(other.propertyStates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (auth_ != null) hash ^= Auth.GetHashCode();
      hash ^= entityProperties_.GetHashCode();
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      hash ^= propertyStates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      if (EntityId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EntityId);
      }
      propertyStates_.WriteTo(output, _repeated_propertyStates_codec);
      entityProperties_.WriteTo(output, _repeated_entityProperties_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      if (EntityId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EntityId);
      }
      propertyStates_.WriteTo(ref output, _repeated_propertyStates_codec);
      entityProperties_.WriteTo(ref output, _repeated_entityProperties_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (auth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      size += entityProperties_.CalculateSize(_repeated_entityProperties_codec);
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
      }
      size += propertyStates_.CalculateSize(_repeated_propertyStates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SetEntityPropertiesRequest other) {
      if (other == null) {
        return;
      }
      if (other.auth_ != null) {
        if (auth_ == null) {
          Auth = new global::Avn.Connect.V1.Authorization();
        }
        Auth.MergeFrom(other.Auth);
      }
      entityProperties_.Add(other.entityProperties_);
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      propertyStates_.Add(other.propertyStates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (auth_ == null) {
              Auth = new global::Avn.Connect.V1.Authorization();
            }
            input.ReadMessage(Auth);
            break;
          }
          case 16: {
            EntityId = input.ReadInt32();
            break;
          }
          case 26: {
            propertyStates_.AddEntriesFrom(input, _repeated_propertyStates_codec);
            break;
          }
          case 34: {
            entityProperties_.AddEntriesFrom(input, _repeated_entityProperties_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (auth_ == null) {
              Auth = new global::Avn.Connect.V1.Authorization();
            }
            input.ReadMessage(Auth);
            break;
          }
          case 16: {
            EntityId = input.ReadInt32();
            break;
          }
          case 26: {
            propertyStates_.AddEntriesFrom(ref input, _repeated_propertyStates_codec);
            break;
          }
          case 34: {
            entityProperties_.AddEntriesFrom(ref input, _repeated_entityProperties_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Bulk property getter to return every requested property from every requested entity
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetEntityPropertiesRequest : pb::IMessage<GetEntityPropertiesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEntityPropertiesRequest> _parser = new pb::MessageParser<GetEntityPropertiesRequest>(() => new GetEntityPropertiesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEntityPropertiesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.PropertiesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityPropertiesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityPropertiesRequest(GetEntityPropertiesRequest other) : this() {
      auth_ = other.auth_ != null ? other.auth_.Clone() : null;
      entityIds_ = other.entityIds_.Clone();
      properties_ = other.properties_.Clone();
      translate_ = other.translate_ != null ? other.translate_.Clone() : null;
      imageSpecs_ = other.imageSpecs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityPropertiesRequest Clone() {
      return new GetEntityPropertiesRequest(this);
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 1;
    private global::Avn.Connect.V1.Authorization auth_;
    /// <summary>
    /// Authorization for the request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.Authorization Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    /// <summary>Field number for the "entity_ids" field.</summary>
    public const int EntityIdsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_entityIds_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> entityIds_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// Entities to inspect. A single request may reference at most 128 entities; larger
    /// requests are rejected. Page through bigger sets in batches of 128 or fewer.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> EntityIds {
      get { return entityIds_; }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.EntityProperty> _repeated_properties_codec
        = pb::FieldCodec.ForEnum(26, x => (int) x, x => (global::Avn.Connect.V1.EntityProperty) x);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.EntityProperty> properties_ = new pbc::RepeatedField<global::Avn.Connect.V1.EntityProperty>();
    /// <summary>
    /// Properties to inspect
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.EntityProperty> Properties {
      get { return properties_; }
    }

    /// <summary>Field number for the "translate" field.</summary>
    public const int TranslateFieldNumber = 4;
    private global::Avn.Connect.V1.TranslationSpec translate_;
    /// <summary>
    /// Translation instructions. The original text is returned if this is unset.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.TranslationSpec Translate {
      get { return translate_; }
      set {
        translate_ = value;
      }
    }

    /// <summary>Field number for the "image_specs" field.</summary>
    public const int ImageSpecsFieldNumber = 5;
    private static readonly pbc::MapField<int, global::Avn.Connect.V1.TranscodeImageSpec>.Codec _map_imageSpecs_codec
        = new pbc::MapField<int, global::Avn.Connect.V1.TranscodeImageSpec>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Avn.Connect.V1.TranscodeImageSpec.Parser), 42);
    private readonly pbc::MapField<int, global::Avn.Connect.V1.TranscodeImageSpec> imageSpecs_ = new pbc::MapField<int, global::Avn.Connect.V1.TranscodeImageSpec>();
    /// <summary>
    /// Image transcode specs by `EntityProperty` ID. If no matching spec is found the original image is returned.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Avn.Connect.V1.TranscodeImageSpec> ImageSpecs {
      get { return imageSpecs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEntityPropertiesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEntityPropertiesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Auth, other.Auth)) return false;
      if(!entityIds_.Equals(other.entityIds_)) return false;
      if(!properties_.Equals(other.properties_)) return false;
      if (!object.Equals(Translate, other.Translate)) return false;
      if (!ImageSpecs.Equals(other.ImageSpecs)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (auth_ != null) hash ^= Auth.GetHashCode();
      hash ^= entityIds_.GetHashCode();
      hash ^= properties_.GetHashCode();
      if (translate_ != null) hash ^= Translate.GetHashCode();
      hash ^= ImageSpecs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      entityIds_.WriteTo(output, _repeated_entityIds_codec);
      properties_.WriteTo(output, _repeated_properties_codec);
      if (translate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Translate);
      }
      imageSpecs_.WriteTo(output, _map_imageSpecs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      entityIds_.WriteTo(ref output, _repeated_entityIds_codec);
      properties_.WriteTo(ref output, _repeated_properties_codec);
      if (translate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Translate);
      }
      imageSpecs_.WriteTo(ref output, _map_imageSpecs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (auth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      size += entityIds_.CalculateSize(_repeated_entityIds_codec);
      size += properties_.CalculateSize(_repeated_properties_codec);
      if (translate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Translate);
      }
      size += imageSpecs_.CalculateSize(_map_imageSpecs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEntityPropertiesRequest other) {
      if (other == null) {
        return;
      }
      if (other.auth_ != null) {
        if (auth_ == null) {
          Auth = new global::Avn.Connect.V1.Authorization();
        }
        Auth.MergeFrom(other.Auth);
      }
      entityIds_.Add(other.entityIds_);
      properties_.Add(other.properties_);
      if (other.translate_ != null) {
        if (translate_ == null) {
          Translate = new global::Avn.Connect.V1.TranslationSpec();
        }
        Translate.MergeFrom(other.Translate);
      }
      imageSpecs_.MergeFrom(other.imageSpecs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (auth_ == null) {
              Auth = new global::Avn.Connect.V1.Authorization();
            }
            input.ReadMessage(Auth);
            break;
          }
          case 18:
          case 16: {
            entityIds_.AddEntriesFrom(input, _repeated_entityIds_codec);
            break;
          }
          case 26:
          case 24: {
            properties_.AddEntriesFrom(input, _repeated_properties_codec);
            break;
          }
          case 34: {
            if (translate_ == null) {
              Translate = new global::Avn.Connect.V1.TranslationSpec();
            }
            input.ReadMessage(Translate);
            break;
          }
          case 42: {
            imageSpecs_.AddEntriesFrom(input, _map_imageSpecs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (auth_ == null) {
              Auth = new global::Avn.Connect.V1.Authorization();
            }
            input.ReadMessage(Auth);
            break;
          }
          case 18:
          case 16: {
            entityIds_.AddEntriesFrom(ref input, _repeated_entityIds_codec);
            break;
          }
          case 26:
          case 24: {
            properties_.AddEntriesFrom(ref input, _repeated_properties_codec);
            break;
          }
          case 34: {
            if (translate_ == null) {
              Translate = new global::Avn.Connect.V1.TranslationSpec();
            }
            input.ReadMessage(Translate);
            break;
          }
          case 42: {
            imageSpecs_.AddEntriesFrom(ref input, _map_imageSpecs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetEntityPropertiesResponse : pb::IMessage<GetEntityPropertiesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEntityPropertiesResponse> _parser = new pb::MessageParser<GetEntityPropertiesResponse>(() => new GetEntityPropertiesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEntityPropertiesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.PropertiesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityPropertiesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityPropertiesResponse(GetEntityPropertiesResponse other) : this() {
      results_ = other.results_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityPropertiesResponse Clone() {
      return new GetEntityPropertiesResponse(this);
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.EntityProperties> _repeated_results_codec
        = pb::FieldCodec.ForMessage(10, global::Avn.Connect.V1.EntityProperties.Parser);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.EntityProperties> results_ = new pbc::RepeatedField<global::Avn.Connect.V1.EntityProperties>();
    /// <summary>
    /// Entity properties read
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.EntityProperties> Results {
      get { return results_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEntityPropertiesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEntityPropertiesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!results_.Equals(other.results_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= results_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      results_.WriteTo(output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      results_.WriteTo(ref output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += results_.CalculateSize(_repeated_results_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEntityPropertiesResponse other) {
      if (other == null) {
        return;
      }
      results_.Add(other.results_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            results_.AddEntriesFrom(ref input, _repeated_results_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityProperties : pb::IMessage<EntityProperties>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityProperties> _parser = new pb::MessageParser<EntityProperties>(() => new EntityProperties());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityProperties> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.PropertiesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityProperties() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityProperties(EntityProperties other) : this() {
      entityId_ = other.entityId_;
      propertyStates_ = other.propertyStates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityProperties Clone() {
      return new EntityProperties(this);
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private int entityId_;
    /// <summary>
    /// Entity ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "property_states" field.</summary>
    public const int PropertyStatesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.EntityPropertyState> _repeated_propertyStates_codec
        = pb::FieldCodec.ForMessage(18, global::Avn.Connect.V1.EntityPropertyState.Parser);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.EntityPropertyState> propertyStates_ = new pbc::RepeatedField<global::Avn.Connect.V1.EntityPropertyState>();
    /// <summary>
    /// Properties of entity
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.EntityPropertyState> PropertyStates {
      get { return propertyStates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityProperties);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityProperties other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if(!propertyStates_.Equals(other.propertyStates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      hash ^= propertyStates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EntityId);
      }
      propertyStates_.WriteTo(output, _repeated_propertyStates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EntityId);
      }
      propertyStates_.WriteTo(ref output, _repeated_propertyStates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
      }
      size += propertyStates_.CalculateSize(_repeated_propertyStates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityProperties other) {
      if (other == null) {
        return;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      propertyStates_.Add(other.propertyStates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EntityId = input.ReadInt32();
            break;
          }
          case 18: {
            propertyStates_.AddEntriesFrom(input, _repeated_propertyStates_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EntityId = input.ReadInt32();
            break;
          }
          case 18: {
            propertyStates_.AddEntriesFrom(ref input, _repeated_propertyStates_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityPropertyState : pb::IMessage<EntityPropertyState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityPropertyState> _parser = new pb::MessageParser<EntityPropertyState>(() => new EntityPropertyState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityPropertyState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.PropertiesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityPropertyState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityPropertyState(EntityPropertyState other) : this() {
      property_ = other.property_;
      switch (other.StateCase) {
        case StateOneofCase.Bool:
          Bool = other.Bool;
          break;
        case StateOneofCase.Int32:
          Int32 = other.Int32;
          break;
        case StateOneofCase.Int64:
          Int64 = other.Int64;
          break;
        case StateOneofCase.Float:
          Float = other.Float;
          break;
        case StateOneofCase.Double:
          Double = other.Double;
          break;
        case StateOneofCase.String:
          String = other.String;
          break;
        case StateOneofCase.Bytes:
          Bytes = other.Bytes;
          break;
        case StateOneofCase.Timestamp:
          Timestamp = other.Timestamp.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityPropertyState Clone() {
      return new EntityPropertyState(this);
    }

    /// <summary>Field number for the "property" field.</summary>
    public const int PropertyFieldNumber = 3;
    private global::Avn.Connect.V1.EntityProperty property_ = global::Avn.Connect.V1.EntityProperty.Unspecified;
    /// <summary>
    /// Entity property
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.EntityProperty Property {
      get { return property_; }
      set {
        property_ = value;
      }
    }

    /// <summary>Field number for the "bool" field.</summary>
    public const int BoolFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Bool {
      get { return HasBool ? (bool) state_ : false; }
      set {
        state_ = value;
        stateCase_ = StateOneofCase.Bool;
      }
    }
    /// <summary>Gets whether the "bool" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBool {
      get { return stateCase_ == StateOneofCase.Bool; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "bool" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBool() {
      if (HasBool) {
        ClearState();
      }
    }

    /// <summary>Field number for the "int32" field.</summary>
    public const int Int32FieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Int32 {
      get { return HasInt32 ? (int) state_ : 0; }
      set {
        state_ = value;
        stateCase_ = StateOneofCase.Int32;
      }
    }
    /// <summary>Gets whether the "int32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInt32 {
      get { return stateCase_ == StateOneofCase.Int32; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "int32" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInt32() {
      if (HasInt32) {
        ClearState();
      }
    }

    /// <summary>Field number for the "int64" field.</summary>
    public const int Int64FieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Int64 {
      get { return HasInt64 ? (long) state_ : 0L; }
      set {
        state_ = value;
        stateCase_ = StateOneofCase.Int64;
      }
    }
    /// <summary>Gets whether the "int64" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInt64 {
      get { return stateCase_ == StateOneofCase.Int64; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "int64" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInt64() {
      if (HasInt64) {
        ClearState();
      }
    }

    /// <summary>Field number for the "float" field.</summary>
    public const int FloatFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Float {
      get { return HasFloat ? (float) state_ : 0F; }
      set {
        state_ = value;
        stateCase_ = StateOneofCase.Float;
      }
    }
    /// <summary>Gets whether the "float" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFloat {
      get { return stateCase_ == StateOneofCase.Float; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "float" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFloat() {
      if (HasFloat) {
        ClearState();
      }
    }

    /// <summary>Field number for the "double" field.</summary>
    public const int DoubleFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Double {
      get { return HasDouble ? (double) state_ : 0D; }
      set {
        state_ = value;
        stateCase_ = StateOneofCase.Double;
      }
    }
    /// <summary>Gets whether the "double" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDouble {
      get { return stateCase_ == StateOneofCase.Double; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "double" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDouble() {
      if (HasDouble) {
        ClearState();
      }
    }

    /// <summary>Field number for the "string" field.</summary>
    public const int StringFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string String {
      get { return HasString ? (string) state_ : ""; }
      set {
        state_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        stateCase_ = StateOneofCase.String;
      }
    }
    /// <summary>Gets whether the "string" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasString {
      get { return stateCase_ == StateOneofCase.String; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "string" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearString() {
      if (HasString) {
        ClearState();
      }
    }

    /// <summary>Field number for the "bytes" field.</summary>
    public const int BytesFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Bytes {
      get { return HasBytes ? (pb::ByteString) state_ : pb::ByteString.Empty; }
      set {
        state_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        stateCase_ = StateOneofCase.Bytes;
      }
    }
    /// <summary>Gets whether the "bytes" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBytes {
      get { return stateCase_ == StateOneofCase.Bytes; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "bytes" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBytes() {
      if (HasBytes) {
        ClearState();
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return stateCase_ == StateOneofCase.Timestamp ? (global::Google.Protobuf.WellKnownTypes.Timestamp) state_ : null; }
      set {
        state_ = value;
        stateCase_ = value == null ? StateOneofCase.None : StateOneofCase.Timestamp;
      }
    }

    private object state_;
    /// <summary>Enum of possible cases for the "state" oneof.</summary>
    public enum StateOneofCase {
      None = 0,
      Bool = 4,
      Int32 = 5,
      Int64 = 6,
      Float = 7,
      Double = 8,
      String = 9,
      Bytes = 10,
      Timestamp = 11,
    }
    private StateOneofCase stateCase_ = StateOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StateOneofCase StateCase {
      get { return stateCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearState() {
      stateCase_ = StateOneofCase.None;
      state_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityPropertyState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityPropertyState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Property != other.Property) return false;
      if (Bool != other.Bool) return false;
      if (Int32 != other.Int32) return false;
      if (Int64 != other.Int64) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Float, other.Float)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Double, other.Double)) return false;
      if (String != other.String) return false;
      if (Bytes != other.Bytes) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (StateCase != other.StateCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) hash ^= Property.GetHashCode();
      if (HasBool) hash ^= Bool.GetHashCode();
      if (HasInt32) hash ^= Int32.GetHashCode();
      if (HasInt64) hash ^= Int64.GetHashCode();
      if (HasFloat) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Float);
      if (HasDouble) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Double);
      if (HasString) hash ^= String.GetHashCode();
      if (HasBytes) hash ^= Bytes.GetHashCode();
      if (stateCase_ == StateOneofCase.Timestamp) hash ^= Timestamp.GetHashCode();
      hash ^= (int) stateCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Property);
      }
      if (HasBool) {
        output.WriteRawTag(32);
        output.WriteBool(Bool);
      }
      if (HasInt32) {
        output.WriteRawTag(40);
        output.WriteInt32(Int32);
      }
      if (HasInt64) {
        output.WriteRawTag(48);
        output.WriteInt64(Int64);
      }
      if (HasFloat) {
        output.WriteRawTag(61);
        output.WriteFloat(Float);
      }
      if (HasDouble) {
        output.WriteRawTag(65);
        output.WriteDouble(Double);
      }
      if (HasString) {
        output.WriteRawTag(74);
        output.WriteString(String);
      }
      if (HasBytes) {
        output.WriteRawTag(82);
        output.WriteBytes(Bytes);
      }
      if (stateCase_ == StateOneofCase.Timestamp) {
        output.WriteRawTag(90);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Property);
      }
      if (HasBool) {
        output.WriteRawTag(32);
        output.WriteBool(Bool);
      }
      if (HasInt32) {
        output.WriteRawTag(40);
        output.WriteInt32(Int32);
      }
      if (HasInt64) {
        output.WriteRawTag(48);
        output.WriteInt64(Int64);
      }
      if (HasFloat) {
        output.WriteRawTag(61);
        output.WriteFloat(Float);
      }
      if (HasDouble) {
        output.WriteRawTag(65);
        output.WriteDouble(Double);
      }
      if (HasString) {
        output.WriteRawTag(74);
        output.WriteString(String);
      }
      if (HasBytes) {
        output.WriteRawTag(82);
        output.WriteBytes(Bytes);
      }
      if (stateCase_ == StateOneofCase.Timestamp) {
        output.WriteRawTag(90);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Property);
      }
      if (HasBool) {
        size += 1 + 1;
      }
      if (HasInt32) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32);
      }
      if (HasInt64) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64);
      }
      if (HasFloat) {
        size += 1 + 4;
      }
      if (HasDouble) {
        size += 1 + 8;
      }
      if (HasString) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
      }
      if (HasBytes) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bytes);
      }
      if (stateCase_ == StateOneofCase.Timestamp) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityPropertyState other) {
      if (other == null) {
        return;
      }
      if (other.Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        Property = other.Property;
      }
      switch (other.StateCase) {
        case StateOneofCase.Bool:
          Bool = other.Bool;
          break;
        case StateOneofCase.Int32:
          Int32 = other.Int32;
          break;
        case StateOneofCase.Int64:
          Int64 = other.Int64;
          break;
        case StateOneofCase.Float:
          Float = other.Float;
          break;
        case StateOneofCase.Double:
          Double = other.Double;
          break;
        case StateOneofCase.String:
          String = other.String;
          break;
        case StateOneofCase.Bytes:
          Bytes = other.Bytes;
          break;
        case StateOneofCase.Timestamp:
          if (Timestamp == null) {
            Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          Timestamp.MergeFrom(other.Timestamp);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            Property = (global::Avn.Connect.V1.EntityProperty) input.ReadEnum();
            break;
          }
          case 32: {
            Bool = input.ReadBool();
            break;
          }
          case 40: {
            Int32 = input.ReadInt32();
            break;
          }
          case 48: {
            Int64 = input.ReadInt64();
            break;
          }
          case 61: {
            Float = input.ReadFloat();
            break;
          }
          case 65: {
            Double = input.ReadDouble();
            break;
          }
          case 74: {
            String = input.ReadString();
            break;
          }
          case 82: {
            Bytes = input.ReadBytes();
            break;
          }
          case 90: {
            global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            if (stateCase_ == StateOneofCase.Timestamp) {
              subBuilder.MergeFrom(Timestamp);
            }
            input.ReadMessage(subBuilder);
            Timestamp = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            Property = (global::Avn.Connect.V1.EntityProperty) input.ReadEnum();
            break;
          }
          case 32: {
            Bool = input.ReadBool();
            break;
          }
          case 40: {
            Int32 = input.ReadInt32();
            break;
          }
          case 48: {
            Int64 = input.ReadInt64();
            break;
          }
          case 61: {
            Float = input.ReadFloat();
            break;
          }
          case 65: {
            Double = input.ReadDouble();
            break;
          }
          case 74: {
            String = input.ReadString();
            break;
          }
          case 82: {
            Bytes = input.ReadBytes();
            break;
          }
          case 90: {
            global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            if (stateCase_ == StateOneofCase.Timestamp) {
              subBuilder.MergeFrom(Timestamp);
            }
            input.ReadMessage(subBuilder);
            Timestamp = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
