// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avn/connect/v1/search.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avn.Connect.V1 {

  /// <summary>Holder for reflection information generated from avn/connect/v1/search.proto</summary>
  public static partial class SearchReflection {

    #region Descriptor
    /// <summary>File descriptor for avn/connect/v1/search.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SearchReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chthdm4vY29ubmVjdC92MS9zZWFyY2gucHJvdG8SDmF2bi5jb25uZWN0LnYx",
            "Gh9hdm4vY29ubmVjdC92MS9wcm9wZXJ0aWVzLnByb3RvIn8KClRleHRTZWFy",
            "Y2gSDAoEdGV4dBgBIAEoCRIyCgpwcm9wZXJ0aWVzGAIgAygOMh4uYXZuLmNv",
            "bm5lY3QudjEuRW50aXR5UHJvcGVydHkSLwoKY29uZGl0aW9ucxgDIAMoDjIb",
            "LmF2bi5jb25uZWN0LnYxLlNlYXJjaEZsYWdzIoIBCgtPcmRlckNsYXVzZRIw",
            "Cghwcm9wZXJ0eRgHIAEoDjIeLmF2bi5jb25uZWN0LnYxLkVudGl0eVByb3Bl",
            "cnR5EjIKCnNvcnRfb3JkZXIYCCABKA4yGS5hdm4uY29ubmVjdC52MS5Tb3J0",
            "T3JkZXJIAIgBAUINCgtfc29ydF9vcmRlcipoCgtTZWFyY2hGbGFncxIcChhT",
            "RUFSQ0hfRkxBR1NfVU5TUEVDSUZJRUQQABIcChhTRUFSQ0hfRkxBR1NfRVhB",
            "Q1RfTUFUQ0gQARIdChlTRUFSQ0hfRkxBR1NfVkVDVE9SX01BVENIEAIqUAoJ",
            "U29ydE9yZGVyEhoKFlNPUlRfT1JERVJfVU5TUEVDSUZJRUQQABISCg5TT1JU",
            "X09SREVSX0FTQxABEhMKD1NPUlRfT1JERVJfREVTQxACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avn.Connect.V1.PropertiesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Avn.Connect.V1.SearchFlags), typeof(global::Avn.Connect.V1.SortOrder), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.TextSearch), global::Avn.Connect.V1.TextSearch.Parser, new[]{ "Text", "Properties", "Conditions" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Avn.Connect.V1.OrderClause), global::Avn.Connect.V1.OrderClause.Parser, new[]{ "Property", "SortOrder" }, new[]{ "SortOrder" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum SearchFlags {
    [pbr::OriginalName("SEARCH_FLAGS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Exact text match
    /// </summary>
    [pbr::OriginalName("SEARCH_FLAGS_EXACT_MATCH")] ExactMatch = 1,
    /// <summary>
    /// Use vector embeddings
    /// </summary>
    [pbr::OriginalName("SEARCH_FLAGS_VECTOR_MATCH")] VectorMatch = 2,
  }

  /// <summary>
  /// Search results ordering
  /// </summary>
  public enum SortOrder {
    [pbr::OriginalName("SORT_ORDER_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Sort results ascending
    /// </summary>
    [pbr::OriginalName("SORT_ORDER_ASC")] Asc = 1,
    /// <summary>
    /// Sort results descending
    /// </summary>
    [pbr::OriginalName("SORT_ORDER_DESC")] Desc = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Text-based search specification
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextSearch : pb::IMessage<TextSearch>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextSearch> _parser = new pb::MessageParser<TextSearch>(() => new TextSearch());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextSearch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.SearchReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextSearch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextSearch(TextSearch other) : this() {
      text_ = other.text_;
      properties_ = other.properties_.Clone();
      conditions_ = other.conditions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextSearch Clone() {
      return new TextSearch(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    /// <summary>
    /// Text to search for
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.EntityProperty> _repeated_properties_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::Avn.Connect.V1.EntityProperty) x);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.EntityProperty> properties_ = new pbc::RepeatedField<global::Avn.Connect.V1.EntityProperty>();
    /// <summary>
    /// Properties to search
    /// Not all properties are available for all content types
    /// If empty a default set of properties will be searched
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.EntityProperty> Properties {
      get { return properties_; }
    }

    /// <summary>Field number for the "conditions" field.</summary>
    public const int ConditionsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Avn.Connect.V1.SearchFlags> _repeated_conditions_codec
        = pb::FieldCodec.ForEnum(26, x => (int) x, x => (global::Avn.Connect.V1.SearchFlags) x);
    private readonly pbc::RepeatedField<global::Avn.Connect.V1.SearchFlags> conditions_ = new pbc::RepeatedField<global::Avn.Connect.V1.SearchFlags>();
    /// <summary>
    /// Search conditions. If unset all matching results will be returned.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Avn.Connect.V1.SearchFlags> Conditions {
      get { return conditions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextSearch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextSearch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      if(!properties_.Equals(other.properties_)) return false;
      if(!conditions_.Equals(other.conditions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      hash ^= properties_.GetHashCode();
      hash ^= conditions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      properties_.WriteTo(output, _repeated_properties_codec);
      conditions_.WriteTo(output, _repeated_conditions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      properties_.WriteTo(ref output, _repeated_properties_codec);
      conditions_.WriteTo(ref output, _repeated_conditions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      size += properties_.CalculateSize(_repeated_properties_codec);
      size += conditions_.CalculateSize(_repeated_conditions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextSearch other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      properties_.Add(other.properties_);
      conditions_.Add(other.conditions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            properties_.AddEntriesFrom(input, _repeated_properties_codec);
            break;
          }
          case 26:
          case 24: {
            conditions_.AddEntriesFrom(input, _repeated_conditions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            properties_.AddEntriesFrom(ref input, _repeated_properties_codec);
            break;
          }
          case 26:
          case 24: {
            conditions_.AddEntriesFrom(ref input, _repeated_conditions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Search results ordering clause
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrderClause : pb::IMessage<OrderClause>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderClause> _parser = new pb::MessageParser<OrderClause>(() => new OrderClause());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderClause> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avn.Connect.V1.SearchReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderClause() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderClause(OrderClause other) : this() {
      _hasBits0 = other._hasBits0;
      property_ = other.property_;
      sortOrder_ = other.sortOrder_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderClause Clone() {
      return new OrderClause(this);
    }

    /// <summary>Field number for the "property" field.</summary>
    public const int PropertyFieldNumber = 7;
    private global::Avn.Connect.V1.EntityProperty property_ = global::Avn.Connect.V1.EntityProperty.Unspecified;
    /// <summary>
    /// Property to order by
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.EntityProperty Property {
      get { return property_; }
      set {
        property_ = value;
      }
    }

    /// <summary>Field number for the "sort_order" field.</summary>
    public const int SortOrderFieldNumber = 8;
    private readonly static global::Avn.Connect.V1.SortOrder SortOrderDefaultValue = global::Avn.Connect.V1.SortOrder.Unspecified;

    private global::Avn.Connect.V1.SortOrder sortOrder_;
    /// <summary>
    /// Order of search results
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Avn.Connect.V1.SortOrder SortOrder {
      get { if ((_hasBits0 & 1) != 0) { return sortOrder_; } else { return SortOrderDefaultValue; } }
      set {
        _hasBits0 |= 1;
        sortOrder_ = value;
      }
    }
    /// <summary>Gets whether the "sort_order" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSortOrder {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "sort_order" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSortOrder() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderClause);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderClause other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Property != other.Property) return false;
      if (SortOrder != other.SortOrder) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) hash ^= Property.GetHashCode();
      if (HasSortOrder) hash ^= SortOrder.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Property);
      }
      if (HasSortOrder) {
        output.WriteRawTag(64);
        output.WriteEnum((int) SortOrder);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Property);
      }
      if (HasSortOrder) {
        output.WriteRawTag(64);
        output.WriteEnum((int) SortOrder);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Property);
      }
      if (HasSortOrder) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SortOrder);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderClause other) {
      if (other == null) {
        return;
      }
      if (other.Property != global::Avn.Connect.V1.EntityProperty.Unspecified) {
        Property = other.Property;
      }
      if (other.HasSortOrder) {
        SortOrder = other.SortOrder;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 56: {
            Property = (global::Avn.Connect.V1.EntityProperty) input.ReadEnum();
            break;
          }
          case 64: {
            SortOrder = (global::Avn.Connect.V1.SortOrder) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 56: {
            Property = (global::Avn.Connect.V1.EntityProperty) input.ReadEnum();
            break;
          }
          case 64: {
            SortOrder = (global::Avn.Connect.V1.SortOrder) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
